NETWORK_IDS = (
    ('43things', '43Things'),
    ('bebo', 'Bebo'),
    ('catster', 'Catster'),
    ('delicious', 'del.icio.us'),
    ('digg', 'Digg'),
    ('dodgeball', 'Dodgeball'),
    ('dogster', 'Dogster'),
    ('dopplr', 'Dopplr'),
    ('facebook', 'Facebook'),
    ('flickr', 'Flickr'),
    ('gamercard', 'Xbox 360 Gamer Card'),
    ('goodreads', 'GoodReads'),
    ('hi5', 'Hi5'),
    ('jaiku', 'Jaiku'),
    ('lastfm', 'Last.fm'),
    ('linkedin', 'LinkedIn'),
    ('lj', 'LiveJournal'),
    ('mog', 'MOG'),
    ('multiply', 'Multiply'),
    ('myspace', 'MySpace'),
    ('newsvine', 'Newsvine'),
    ('ning', 'Ning'),
    ('orkut', 'Orkut'),
    ('pandora', 'Pandora'),
    ('pownce', 'Pownce'),
    ('reddit', 'Reddit'),
    ('sonicliving', 'SonicLiving'),
    ('stumbleupon', 'StumbleUpon'),
    ('tabblo', 'Tabblo'),
    ('tagworld', 'TagWorld'),
    ('technorati', 'Technorati'),
    ('tribe', 'Tribe'),
    ('twitter', 'Twitter'),
    ('upcoming', 'Upcoming'),
    ('vox', 'Vox'),
    ('youtube', 'YouTube'),
    ('zooomr', 'Zooomr'),
)

NETWORK_URLS = {
    '43things':'http://www.43things.com/person/%s/',
    'bebo':'http://www.bebo.com/Profile.jsp?MemberId=%s',
    'catster':'http://www.catster.com/cats/%s',
    'delicious':'http://del.icio.us/%s/',
    'digg':'http://digg.com/users/%s/',
    'dodgeball':'http://www.dodgeball.com/user?uid=%s',
    'dogster':'http://www.dogster.com/dogs/%s',
    'dopplr':'http://www.dopplr.com/traveller/%s/',
    'facebook':'http://www.facebook.com/profile.php?id=%s',
    'flickr':'http://flickr.com/photos/%s/',
    'gamercard':'http://live.xbox.com/en-US/profile/profile.aspx?pp=0&GamerTag=%s',
    'goodreads':'http://www.goodreads.com/user/show/%s',
    'hi5':'http://hi5.com/friend/profile/displayProfile.do?userid=%s',
    'jaiku':'http://%s.jaiku.com/',
    'lastfm':'http://www.last.fm/user/%s/',
    'linkedin':'http://www.linkedin.com/in/%s',
    'lj':'http://%s.livejournal.com/',
    'mog':'http://mog.com/%s',
    'multiply':'http://%s.multiply.com/',
    'myspace':'http://www.myspace.com/%s',
    'newsvine':'http://%s.newsvine.com/',
    'ning':'http://%s.ning.com/',
    'orkut':'http://www.orkut.com/Profile.aspx?uid=%s',
    'pandora':'http://pandora.com/people/%s',
    'pownce':'http://pownce.com/%s/',
    'reddit':'http://reddit.com/user/%s/',
    'sonicliving':'http://www.sonicliving.com/user/%s/',
    'stumbleupon':'http://%s.stumbleupon.com/',
    'tabblo':'http://www.tabblo.com/studio/person/%s/',
    'tagworld':'http://www.tagworld.com/%s',
    'technorati':'http://technorati.com/people/technorati/%s',
    'tribe':'http://people.tribe.net/%s',
    'twitter':'http://twitter.com/%s',
    'upcoming':'http://upcoming.yahoo.com/user/%s',
    'vox':'http://%s.vox.com/',
    'youtube':'http://www.youtube.com/user/%s',
    'zooomr':'http://www.zooomr.com/photos/%s',
}

NETWORK_IDENTIFIERS = (
    ('43things', 'Username'),
    ('bebo', 'Member ID'),
    ('catster', 'Cat ID'),
    ('delicious', 'Username'),
    ('digg', 'Username'),
    ('dodgeball', 'User ID'),
    ('dogster', 'Dog ID'),
    ('dopplr', 'Username'),
    ('facebook', 'User ID'),
    ('flickr', 'Flickr Alias'),
    ('gamercard', 'Gamertag'),
    ('goodreads', 'User ID'),
    ('hi5', 'User ID'),
    ('jaiku', 'Username'),
    ('lastfm', 'Username'),
    ('linkedin', 'Full Name (without spaces)'),
    ('lj', 'Username'),
    ('mog', 'Username'),
    ('multiply', 'Username'),
    ('myspace', 'Username'),
    ('newsvine', 'Username'),
    ('ning', 'Network Name'),
    ('orkut', 'User ID'),
    ('pandora', 'Username'),
    ('pownce', 'Username'),
    ('reddit', 'Username'),
    ('sonicliving', 'User ID'),
    ('stumbleupon', 'Username'),
    ('tabblo', 'Username'),
    ('tagworld', 'Username'),
    ('technorati', 'Username'),
    ('tribe', 'Username'),
    ('twitter', 'Username'),
    ('upcoming', 'User ID'),
    ('vox', 'Username'),
    ('youtube', 'Username'),
    ('zooomr', 'Username'),
)

MESSENGER_IDS = (
    ('aim', 'AIM'),
    ('msn', 'MSN Messenger'),
    ('yahoo', 'Yahoo! Messenger'),
    ('gtalk', 'GTalk'),
    ('icq', 'ICQ'),
    ('skype', 'Skype'),
)

MESSENGER_URLS = {
    'aim':'aim:goim?screenname=%s',
    'msn':'msnim:chat?contact=%s',
    'yahoo':'ymsgr:sendim?%s',
    'gtalk':'gtalk:chat?jid=%s',
    'icq':'http://www.icq.com/people/about_me.php?to=%s',
    'skype':'skype:%s?chat',
}

MESSENGER_NAMES = {
    'aim': 'AIM',
    'msn': 'MSN',
    'yahoo': 'Y!',
    'gtalk': 'GTalk',
    'icq': 'ICQ',
    'skype': 'Skype',
}